### ISSUE TITLE
[FEAT] Board Main Page Implement

### ISSUE THREAD

**Issue by selfishAltruism** [CAUCSE/CAUSW_frontend_V2#6]
### 목적

> Navigation bar에서 게시판 선택 나타나는 기본 페이지 구현

### 작업 상세 내용

- [x] Borad main page UI 구현
- [ ] 기존의 API 형태 유지하면서 최근 게시판과 내가 작성한 글 API method 구현
- [ ] 최근 게시판과 내가 작성한 글 서버와 연결하면서 정상적으로 전시되는지 확인
- [ ] 찜한 게시물 서버와 API 합의
- [ ] 찜한 게시물 API method 구현
- [ ] 찜한 게시물 서버와 연결하면서 정상적으로 전시되는지 확인

### 유의사항
- 기획 디자인 팀 결과물 기준으로 구현
![image](https://github.com/user-attachments/assets/c076c7b9-640f-4093-8f2d-212bcd9e83d0)
- 우측 사이트 바와 Navigation bar는 구현 할 필요 없음
- 찜한 게시물 개념이 기존에는 없던 기능이기 때문에 백엔드 팀과 조율 필요

**Comment by lee0jae330** [comment]
허걱

**Comment by lee0jae330** [comment]
사이드바 색깔이 조금 더 진하면 좋겠습니다

**Comment by selfishAltruism** [comment]
다들 고생 많으셨습니다! 😎
