### ISSUE TITLE
[FIX] 게시판 메인 화면에서 게시글 클릭 시 게시글 제목에만 <a> 태그가 적용되는 문제 발생

### ISSUE THREAD

**Issue by lee0jae330** [CAUCSE/CAUSW_frontend_V2#62]
### 목적

> 게시판 메인 화면에서 게시글 클릭 시 게시글 제목에만 <a> 태그가 적용되는 문제 발생

![image](https://github.com/user-attachments/assets/aacd2b2e-b622-4a16-b9c2-446a3c4fd9fa)

### 작업 상세 내용
- [ ]  게시글 제목이 있는 줄 전체에 <a> 태그 적용
- [ ]
- [ ]

**Comment by selfishAltruism** [comment]
다들 고생 많으셨습니다! 😎
