### ISSUE TITLE
[FEAT] 각 게시판의 게시글 목록에서 이미지가 첨부된 게시글에 썸네일 기능 추가

### ISSUE THREAD

**Issue by lee0jae330** [CAUCSE/CAUSW_frontend_V2#64]
### 목적

> 게시판 게시글 목록에서 이미지가 첨부된 게시글에 썸네일 기능 추가

### 작업 상세 내용

- [x] 게시글 목록에서 이미지가 첨부된 게시글이라면 첨부된 이미지를 썸네일로 지정
  - 사진이 없는 게시글이라면 푸앙이 사진을 썸네일로 지정

**Comment by selfishAltruism** [comment]
다들 고생 많으셨습니다! 😎
